### model
model_name_or_path: /jyx_data/models/Qwen/Qwen3.5-35B-A3B-Base
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: swelego_chaofan_glm5_swegen_cc_2135,swelego_chaofan_glm5_swegen_oc_1177,swelego_chaofan_glm5_swegen_ohsdk_1140,swelego_jierun_glm5_swerebenchv2_python_oraclesolved_cc_2728,swelego_jierun_glm5_swerebenchv2_python_oraclesolved_oc_1654,swelego_jierun_glm5_swerebenchv2_python_oraclesolved_oh_sdk_1521,swelego_jierun_glm5_v2nopy_full_cc_5128,swelego_jierun_glm5_v2nopy_full_oc_3465,swelego_jierun_glm5_v2nopy_full_oh_sdk_3266
template: qwen3_5_nothink
cutoff_len: 131072
rope_scaling: yarn
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen3_5_35b_a3b_base_selfmade_traj_selected_gbs64pbs1acc8_lr5e-5_epo3
logging_steps: 1
save_strategy: steps
save_steps: 100
save_total_limit: 3
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
weight_decay: 0.01
max_grad_norm: 1.0
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
enable_liger_kernel: true
use_unsloth_gc: true
flash_attn: fa2

# push_to_hub: true
# hub_model_id: SWE-Lego/qwen3_5_35b_a3b_base_selfmade_traj_selected_gbs64pbs1acc8_lr5e-5_epo3
# hub_private_repo: private
# hub_token: <set via HF_TOKEN env or huggingface-cli login>